inputs:
  test1_txt:
    path: data/test1.txt
  test1:
    path: data/test1
parameters:
  parameter1:
    default_value: 1.0
  parameter2:
    default_value: 1.0
step: 9
docker_image: test_mosorio:latest
github_repo_url: https://github.com/sirspock/test_mosorio.git
version: 20.5.16
